package com.revature.models;


public class User {

	// instance variable
	private String username;
	private String password;
	private int age;
	private Task[] tasks = new Task[3]; // Each user can only have 3 tasks

	//// Setter & Getter
	public int getAge() {
		return age;
	}

	public void setAge(int age) {
		if (age < 0) {
			this.age = 0;
		} else {
			this.age = age;
		}
	}

	///////////////////

	// static variable
	public static int numberOfUsers;

//////Autogenerated setters&getters

	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}
	
	

	/////////////
	


	public Task[] getTasks() {
		return tasks;
	}

	public void setTasks(Task[] tasks) {
		this.tasks = tasks;
	}

	public void setTask(Task t1) {
		// TODO Auto-generated method stub
		
	}
}